FROM python:3.12.10-bullseye

# Copy code over
COPY app.py /app.py
COPY classes.py /classes.py
COPY requirements.txt /requirements.txt
COPY styles.css /styles.css

# Clean up the default home directory and set up a new one
ENV GITHUB_WORKSPACE=/home
ENV GITHUB_REPOSITORY=hinkleydev/sade-ci

RUN rm -rf /home && mkdir /home
WORKDIR /home

# Clone the example repository
RUN git clone https://github.com/hinkleydev/sade-ci.git .

# Install dependencies
RUN pip install -r /requirements.txt

# Generate the docs
RUN python3 /app.py

# Serve the docs
EXPOSE 8080
ENTRYPOINT ["python3", "-m", "http.server", "-d", "docs"]