name: Dependency scan

on: [push]
jobs:
  selftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install
        run: python -m pip install .
      - uses: pypa/gh-action-pip-audit@v1.1.0
